/** Optional loopback browser transport. No signing, poker decisions or settlement.
 * Its configured gateway is supplied by the local operator (a simulator in tests).
 * One browser connection replaces a headless agent, not the table protocol.
 */
import { WebSocket, WebSocketServer } from "ws";
import { ensureCapacity, type FiberGateway } from "@fiber-poker/fiber-adapter";

export interface CompanionConfig {
  tableUrl: string;
  playerId: string;
  gateway: FiberGateway;
  port?: number;
  allowedOrigins: string[];
  /** Explicit local operator opt-in. Defaults to observing requests only. */
  payInvoices?: boolean;
  /** Identity GENERATED by this companion run (--generate-identity). Only
   *  this may be served to the loopback browser on IDENTITY_REQUEST —
   *  operator-provided identity files are never exposed over the wire. */
  generatedIdentity?: { privateKey: string; publicKey: string };
  /** Shared funding: MULTIPLE player identities served from one process
   *  (one browser per identity). Generated entries are served on
   *  IDENTITY_REQUEST round-robin; every invoice paid is recorded in the
   *  per-player spend ledger for operator settlement. */
  players?: { privateKey: string; publicKey: string; generated: boolean }[];
  /** On-ramp: player-side capacity to ensure toward the table once the
   *  table's fiber peer is known (WELCOME). Off when absent or zero. */
  minCapacityShannons?: bigint;
  /** Funding for a compensating open when capacity is short (default 600 CKB). */
  capacityOpenFundingShannons?: bigint;
}
export class PlayerCompanion {
  private listener: WebSocketServer | null = null;
  /** One browser per served identity (shared funding: N players, N tabs). */
  private browsers = new Set<WebSocket>();
  private browserPlayers = new Map<WebSocket, string>();
  private upstream: WebSocket | null = null;
  private peer = "";
  /** The table's FIBER node pubkey (from the upstream WELCOME) — capacity
   *  target for auto-provisioning when a payment would outrun the pool. */
  private tableFiberPeer = "";
  private payments = new Map<string, Promise<void>>();
  private stopped = false;
  /** Shared funding: the identities this companion serves. Built from
   *  `players` (multi-player) or the single-player fields. */
  private readonly pool: {
    publicKey: string;
    privateKey: string;
    generated: boolean;
    claimed: boolean;
  }[] = [];
  /** Per-player spend ledger: every invoice this companion paid, attributed
   *  to the paying identity. Cash-outs are settled by the operator by
   *  joining obligationIds against the table's event log. */
  private readonly ledger: {
    playerId: string;
    obligationId: string;
    reason: string;
    amountShannons: string;
    paidAt: string;
  }[] = [];
  constructor(private readonly config: CompanionConfig) {
    const generated = config.generatedIdentity;
    if (generated) {
      this.pool.push({
        publicKey: generated.publicKey,
        privateKey: generated.privateKey,
        generated: true,
        claimed: false,
      });
    }
    for (const p of config.players ?? []) {
      if (this.pool.some((e) => e.publicKey === p.publicKey)) continue;
      this.pool.push({
        publicKey: p.publicKey,
        privateKey: p.privateKey,
        generated: p.generated,
        claimed: false,
      });
    }
    // Legacy single-player config: the configured identity is served for
    // authentication but never handed out over the wire.
    if (this.pool.length === 0 && config.playerId) {
      this.pool.push({
        publicKey: config.playerId,
        privateKey: "",
        generated: false,
        claimed: false,
      });
    }
  }

  /** Per-player spend ledger (operator settlement). */
  exportLedger(): {
    playerId: string;
    obligationId: string;
    reason: string;
    amountShannons: string;
    paidAt: string;
  }[] {
    return this.ledger.map((e) => ({ ...e }));
  }
  get port(): number {
    const address = this.listener?.address();
    return address && typeof address !== "string" ? address.port : 0;
  }
  async start(): Promise<void> {
    this.peer = await this.config.gateway.nodePubkey();
    this.listener = new WebSocketServer({
      host: "127.0.0.1",
      port: this.config.port ?? 8788,
      maxPayload: 64 * 1024,
      verifyClient: ({ origin }, done) => {
        if (!this.config.allowedOrigins.includes(origin))
          return done(false, 403, "Origin not allowed");
        // One browser per served identity; a second tab for the SAME
        // identity would replace its table session (SessionManager).
        if (this.browsers.size >= this.pool.length)
          return done(false, 409, "Every served identity already has a browser");
        done(true);
      },
    });
    this.listener.on("connection", (browser) => this.attach(browser));
    await new Promise<void>((resolve, reject) => {
      this.listener!.once("listening", resolve);
      this.listener!.once("error", reject);
    });
  }
  private attach(browser: WebSocket): void {
    if (this.browsers.size >= this.pool.length) {
      browser.close(1009, "Every served identity already has a browser");
      return;
    }
    this.browsers.add(browser);
    let upstream: WebSocket | null = null;
    let authenticated = false;
    /** The identity this browser authenticated with (pool member). */
    let connectionPlayer = "";
    const queued: string[] = [];
    const timer = setTimeout(
      () => browser.close(1008, "Authentication timeout"),
      15000,
    );
    const fail = (code: string, detail: string) => {
      this.send(browser, "ERROR", { code, detail });
      browser.close(1008, code);
    };
    browser.on("message", (data) => {
      let message: { type: string; payload: Record<string, unknown> };
      try {
        message = JSON.parse(data.toString());
        if (!message.payload || typeof message.payload !== "object")
          throw new Error();
      } catch {
        fail("COMPANION_BAD_MESSAGE", "Invalid poker message.");
        return;
      }
      // On-ramp: the loopback browser may request an identity THIS run
      // generated (round-robin from the pool). Operator-provided identity
      // files are never served over the wire.
      if (message.type === "IDENTITY_REQUEST") {
        const anyGenerated = this.pool.some((e) => e.generated);
        const free = this.pool.find((e) => e.generated && !e.claimed);
        if (!free) {
          // Distinguish "no on-ramp configured" from "pool exhausted" so the
          // browser can tell the operator what to change.
          const code = anyGenerated ? "COMPANION_NO_FREE_IDENTITY" : "COMPANION_IDENTITY_DISABLED";
          fail(
            code,
            anyGenerated
              ? "Every generated identity is in use; run the companion with --players N for more."
              : "This companion did not generate an identity; use --generate-identity.",
          );
          return;
        }
        free.claimed = true;
        this.send(browser, "IDENTITY", {
          privateKey: free.privateKey,
          publicKey: free.publicKey,
          generated: true,
        });
        return;
      }
      if (message.type === "HELLO") authenticated = false;
      if (
        ["HELLO", "AUTH_RESPONSE"].includes(message.type) &&
        !this.pool.some((e) => e.publicKey === message.payload.pubkey)
      ) {
        fail("COMPANION_KEY_MISMATCH", "The companion only serves its configured poker identities.");
        return;
      }
      if (message.type === "HELLO") {
        connectionPlayer = String(message.payload.pubkey ?? "");
        const member = this.pool.find((e) => e.publicKey === connectionPlayer);
        if (member) member.claimed = true;
        this.browserPlayers.set(browser, connectionPlayer);
      }
      if (!upstream) {
        if (
          message.type !== "HELLO" ||
          !this.pool.some((e) => e.publicKey === message.payload.pubkey)
        ) {
          fail(
            "COMPANION_KEY_MISMATCH",
            "Choose the companion's matching .session.json poker identity file.",
          );
          return;
        }
        upstream = new WebSocket(this.config.tableUrl, {
          maxPayload: 1024 * 1024,
          handshakeTimeout: 10000,
        });
        this.upstream = upstream;
        const remote = upstream;
        remote.on("open", () => {
          for (const item of queued) remote.send(item);
          queued.length = 0;
        });
        remote.on("message", (raw) => {
          let incoming: { type: string; payload: Record<string, unknown> };
          try {
            incoming = JSON.parse(raw.toString());
          } catch {
            remote.close(1002, "Invalid table message");
            return;
          }
          if (incoming.type === "WELCOME") {
            authenticated = true;
            clearTimeout(timer);
            const fiberPeer = (incoming.payload as { fiberPeerPubkey?: string }).fiberPeerPubkey;
            if (fiberPeer) this.tableFiberPeer = fiberPeer;
            // On-ramp: make sure this node can actually PAY at the table
            // before the player tries to join (rc7 has no post-open funding).
            const min = this.config.minCapacityShannons ?? 0n;
            if (fiberPeer && min > 0n) {
              this.send(browser, "COMPANION_STATUS", { status: "PROVISIONING_CAPACITY" });
              void ensureCapacity(this.config.gateway, fiberPeer, {
                min,
                openFunding: this.config.capacityOpenFundingShannons ?? 600n * 100_000_000n,
              })
                .then(() => {
                  this.send(browser, "COMPANION_STATUS", { status: "CAPACITY_READY" });
                })
                .catch((e) => {
                  this.send(browser, "COMPANION_STATUS", {
                    status: "CAPACITY_FAILED",
                    detail: String(e),
                  });
                });
            }
          }
          if (browser.readyState === WebSocket.OPEN)
            browser.send(raw.toString());
          if (incoming.type === "WELCOME")
            this.send(browser, "COMPANION_STATUS", {
              status: this.config.payInvoices ? "READY" : "OBSERVE_ONLY",
            });
          if (authenticated && incoming.type === "PAYMENT_REQUIRED")
            this.pay(incoming.payload, browser, connectionPlayer);
        });
        remote.on("error", () =>
          fail(
            "COMPANION_TABLE_UNAVAILABLE",
            "The companion could not connect to the table.",
          ),
        );
        remote.on("close", () =>
          browser.close(1012, "Table connection closed"),
        );
      }
      if (message.type === "JOIN_TABLE") {
        if (!authenticated) {
          fail("COMPANION_NOT_AUTHENTICATED", "Authenticate before joining.");
          return;
        }
        message.payload = { ...message.payload, fiberPeerPubkey: this.peer };
      }
      const serialized = JSON.stringify(message);
      if (upstream.readyState === WebSocket.OPEN) upstream.send(serialized);
      else if (
        upstream.readyState === WebSocket.CONNECTING &&
        queued.length < 16
      )
        queued.push(serialized);
      else
        fail(
          "COMPANION_UNAVAILABLE",
          "The companion is reconnecting to the table.",
        );
    });
    browser.on("error", () => browser.close());
    browser.on("close", () => {
      clearTimeout(timer);
      if (upstream?.readyState === WebSocket.CONNECTING) upstream.terminate();
      else upstream?.close();
      this.browsers.delete(browser);
      this.browserPlayers.delete(browser);
    });
  }
  private pay(
    payload: Record<string, unknown>,
    browser: WebSocket,
    connectionPlayer: string,
  ): void {
    if (
      this.stopped ||
      !this.config.payInvoices ||
      payload.direction !== "PLAYER_TO_TABLE" ||
      typeof payload.invoiceAddress !== "string" ||
      typeof payload.obligationId !== "string"
    )
      return;
    const id = payload.obligationId;
    if (this.payments.has(id)) return;
    this.send(browser, "COMPANION_STATUS", {
      status: "PAYMENT_SUBMITTING",
      obligationId: id,
    });
    // Start after insertion so even synchronous gateway failures are retryable.
    const task = Promise.resolve().then(async () => {
      const amount = BigInt(String(payload.amountShannons ?? "0"));
      const attempt = async (): Promise<void> => {
        if (!this.config.gateway.payInvoice)
          throw new Error("Invoice payment unavailable");
        await this.config.gateway.payInvoice(payload.invoiceAddress as string);
      };
      try {
        await attempt();
        this.ledger.push({
          playerId: connectionPlayer,
          obligationId: id,
          reason: String(payload.reason ?? ""),
          amountShannons: String(payload.amountShannons ?? "0"),
          paidAt: new Date().toISOString(),
        });
        this.send(browser, "COMPANION_STATUS", {
          status: "PAYMENT_SUBMITTED",
          obligationId: id,
        });
      } catch (error) {
        // Insufficient player-side capacity: provision toward the table and
        // retry once before reporting failure (capacity.ts).
        const insufficient = /insufficient/i.test(String(error));
        if (insufficient && this.tableFiberPeer) {
          try {
            await ensureCapacity(this.config.gateway, this.tableFiberPeer, {
              min: amount > 0n ? amount * 2n : 50n * 100_000_000n,
              openFunding: 600n * 100_000_000n,
            });
            await attempt();
            this.send(browser, "COMPANION_STATUS", {
              status: "PAYMENT_SUBMITTED",
              obligationId: id,
            });
            return;
          } catch {
            /* fall through to failure */
          }
        }
        this.send(browser, "COMPANION_STATUS", {
          status: "PAYMENT_FAILED",
          obligationId: id,
        });
        this.payments.delete(id);
      }
    });
    this.payments.set(id, task);
    if (this.payments.size > 512) {
      const oldest = this.payments.keys().next().value!;
      void this.payments.get(oldest)!.then(() => this.payments.delete(oldest));
    }
  }
  private send(
    socket: WebSocket,
    type: string,
    payload: Record<string, unknown>,
  ): void {
    if (socket.readyState === WebSocket.OPEN)
      socket.send(JSON.stringify({ type, payload }));
  }
  async stop(): Promise<void> {
    this.stopped = true;
    for (const browser of this.browsers) browser.terminate();
    this.upstream?.terminate();
    await new Promise<void>((resolve) =>
      this.listener ? this.listener.close(() => resolve()) : resolve(),
    );
  }
}
